name: "standard_github_lesson_repo002"

on:
  push:
    branches:
      - main
    paths:
      - working/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: "working/" # terraformを実行するディレクトリ

jobs:
  sample:
    name: Hello World Job
    runs-on: ubuntu-latest
    environment: production # 承認フロー
    steps:
      - name: Cehckout repository
        uses: actions/checkout@v3
      - name: Echo hello
        run:  |
          echo "Hello World !"


